### ISSUE TITLE
Error in rule infer_relative_usage UnboundLocalError: local variable 'end_idx' referenced before assignment

### ISSUE THREAD

**Issue by aleighbrown** [zavolanlab/PAQR_KAPAC#9]
```
############## Started script on 12-11-2019 at 11:39:43 ##############
[INFO] Tue Nov 12 11:40:52 2019 Finished reading input
[INFO] Distal site skipped due to conflicting global break points in all samples in exon ENSMUST00000045887:3:3:71330480:71331126. Skipped exon!
[INFO] No site was inferred for ENSMUST00000115417:15:15:17942670:17943020. Skipped exon!
Traceback (most recent call last):
  File "scripts/deNovo-used-sites-and-usage-inference.single_distal_included.py", line 2302, in <module>
    main(options)
  File "scripts/deNovo-used-sites-and-usage-inference.single_distal_included.py", line 2118, in main
    result_tuples = pool.map( process_exon_wrapper_function, data_entries)
  File "/SAN/vyplab/alb_projects/tools/.conda/envs/py2_paqr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/SAN/vyplab/alb_projects/tools/.conda/envs/py2_paqr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
UnboundLocalError: local variable 'end_idx' referenced before assignment
```

**Comment by koljaLanger** [comment]
Many thanks for the report. I'll have a look into it as soon as possible.

**Comment by yangjywhu** [comment]
I have the same problem.

**Comment by koljaLanger** [comment]
I have created the branch "end_idx_fix" with an updated version of the `deNovo-used-sites-and-usage-inference.single_distal_included.py` script. Can you please checkout this branch and test if the problem is resolved?
Many thanks for your help!
Ralf

**Comment by aleighbrown** [comment]
Updated version of the deNovo-used-sites-and-usage-inference.single_distal_included.py fixes the bug


We are getting a lot of messages like this:
```
############## Started script on 27-11-2019 at 11:32:56 ##############
[INFO] Wed Nov 27 11:34:29 2019 Finished reading input
[INFO] Distal site skipped due to conflicting global break points in all samples in exon ENSMUST00000045887:3:3:71330480:71331126. Skipped exon!
[INFO] No site was inferred for ENSMUST00000115417:15:15:17942670:17943020. Skipped exon!
[INFO] No site was inferred for ENSMUST00000031617:7:7:121208782:121209241. Skipped exon!
[INFO] No site was inferred for ENSMUST00000087012:10:10:46432185:46432517. Skipped exon!
[INFO] For exon ENSMUST00000163119:16:16:80264923:80267287, 3 samples are not further processed due to unsupported global break points in their coverage```
